server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

spring:
  cloud:
    gateway:
      routes:
        - id: academy-service
          uri: lb://academy-service
          predicates:
            - Path=/academy/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
